require('plugin-config/nvim-tree')
require('plugin-config/bufferline')
require('plugin-config/nvim-treesitter')
require('plugin-config/Comment')
require('plugin-config/telescope')
require('plugin-config/nvim-autopairs')
require('plugin-config/indent_blankline')
require('plugin-config/nvim-colorizer')
require('plugin-config/lualine')
require('plugin-config/toggleterm')
require('plugin-config/AutoSave')
require('plugin-config/hop')
require('plugin-config/format')
require('plugin-config/which-key')
require'impatient'.enable_profile()

require('lsp/setup')
require('lsp/nvim-cmp')
