return {
    "stevearc/aerial.nvim",
    keys = {
        { "[f", "<cmd>AerialPrev<CR>", desc = "Previous symbol" },
        { "]f", "<cmd>AerialNext<CR>", desc = "Next symbol" },
        { "<leader>aa", "<cmd>AerialToggle<CR>", desc = "Toggle aerial" },
    },
    opts = {
        backends = { "lsp", "treesitter", "markdown" },
        icons = require("utils.lspkind").icons,
        filter_kind = {
            "Array",
            "Boolean",
            "Class",
            "Constant",
            "Constructor",
            "Enum",
            "EnumMember",
            "Event",
            "Field",
            "File",
            "Function",
            "Interface",
            "Key",
            "Method",
            "Module",
            "Namespace",
            "Null",
            "Number",
            "Object",
            "Operator",
            "Package",
            "Property",
            -- "String",
            "Struct",
            "TypeParameter",
            "Variable",
        },

        show_guides = true,
    },
}
