--- Treesitter captures, markup/text groups, LSP diagnostics and semantic tokens.
local M = {}

---@param p table palette
---@return table<string, table>
function M.get(p)
    return {
        ------------------------------------------------------------------
        -- LSP diagnostics
        ------------------------------------------------------------------
        MsgUnderline = { sp = p.green, undercurl = true },
        MoreMsgUnderline = { sp = p.blue, undercurl = true },
        ErrorMsgUnderline = { sp = p.red, undercurl = true },
        WarningMsgUnderline = { sp = p.yellow, undercurl = true },

        LspCodeLens = { fg = p.grey },
        LspHighlight = { bg = p.bg_hl }, -- CurrentWord, everforest style
        LspInlayHint = { fg = p.grey },
        LspReferenceText = { link = "LspHighlight" },
        LspReferenceRead = { link = "LspHighlight" },
        LspReferenceWrite = { link = "LspHighlight" },
        LspSignatureActiveParameter = { fg = p.orange, bold = true },

        DiagnosticOk = { link = "Msg" },
        DiagnosticHint = { fg = p.grey },
        DiagnosticInfo = { fg = p.blue },
        DiagnosticWarn = { fg = p.yellow },
        DiagnosticError = { fg = p.red },
        DiagnosticSignOk = { link = "DiagnosticOk" },
        DiagnosticSignHint = { link = "DiagnosticHint" },
        DiagnosticSignInfo = { link = "DiagnosticInfo" },
        DiagnosticSignWarn = { link = "DiagnosticWarn" },
        DiagnosticSignError = { link = "DiagnosticError" },
        DiagnosticFloatingOk = { link = "DiagnosticOk" },
        DiagnosticFloatingHint = { link = "DiagnosticHint" },
        DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
        DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
        DiagnosticFloatingError = { link = "DiagnosticError" },
        DiagnosticUnderlineOk = { link = "MsgUnderline" },
        DiagnosticUnderlineHint = { sp = p.grey, undercurl = true },
        DiagnosticUnderlineInfo = { link = "MoreMsgUnderline" },
        DiagnosticUnderlineWarn = { link = "WarningMsgUnderline" },
        DiagnosticUnderlineError = { link = "ErrorMsgUnderline" },
        DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
        DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
        DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
        DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
        DiagnosticVirtualTextError = { link = "DiagnosticError" },
        DiagnosticUnnecessary = { fg = p.grey },
        DiagnosticDeprecated = { strikethrough = true, sp = p.fg },

        ------------------------------------------------------------------
        -- LSP semantic tokens (follow the treesitter captures)
        ------------------------------------------------------------------
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.events"] = { link = "@type" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.interface"] = { link = "@type" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type" },
        ["@lsp.type.typeAlias"] = { link = "@type.definition" },
        ["@lsp.type.builtinType"] = { link = "@type.builtin" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.event"] = { link = "@type" },
        ["@lsp.type.regexp"] = { link = "@string.regex" },
        ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
        ["@lsp.type.selfParameter"] = { link = "@variable.builtin" },
        ["@lsp.type.modifier"] = { link = "@keyword" },
        ["@lsp.type.parameter"] = { link = "@variable.parameter" },
        ["@lsp.type.variable"] = { link = "@variable" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.macro"] = { link = "@constant.macro" },
        ["@lsp.type.decorator"] = { link = "@attribute" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.operator"] = { link = "@operator" },
        ["@lsp.type.number"] = { link = "@number" },
        ["@lsp.type.boolean"] = { link = "@boolean" },
        ["@lsp.type.string"] = { link = "@string" },
        ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
        ["@lsp.type.formatSpecifier"] = { link = "@punctuation.special" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.unresolvedReference"] = { link = "@error" },

        ------------------------------------------------------------------
        -- Treesitter captures
        ------------------------------------------------------------------
        ["@error"] = { fg = p.red, bold = true },
        ["@none"] = { fg = p.fg },

        ["@keyword"] = { link = "Keyword" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.operator"] = { link = "@operator" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.export"] = { link = "Include" },
        ["@keyword.modifier"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },

        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "FunctionBuiltin" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@function.method.call"] = { link = "Function" },
        ["@method"] = { link = "Method" },
        ["@method.call"] = { link = "Method" },
        ["@constructor"] = { link = "Constructor" },

        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "TypeBuiltin" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@storageclass.lifetime"] = { link = "StorageClass" },

        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Constant" },
        ["@constant.macro"] = { link = "Define" },

        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@boolean"] = { link = "Boolean" },

        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.url"] = { link = "URL" },
        ["@string.special.uri"] = { link = "URL" },
        ["@string.documentation"] = { link = "String" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@uri"] = { link = "URL" },

        ["@variable"] = { link = "Variable" },
        ["@variable.builtin"] = { link = "VariableBuiltin" },
        ["@variable.parameter"] = { link = "Argument" },
        ["@parameter.reference"] = { link = "Argument" },
        ["@variable.member"] = { link = "Field" },
        ["@variable.function"] = { link = "Argument" },
        ["@identifier"] = { link = "Identifier" },
        ["@symbol"] = { link = "Identifier" },

        ["@property"] = { link = "Property" },
        ["@field"] = { link = "Field" },
        ["@attribute"] = { link = "Attribute" },
        ["@annotation"] = { link = "PreProc" },

        ["@include"] = { link = "Include" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@macro"] = { link = "Macro" },
        ["@module"] = { link = "Include" },
        ["@module.builtin"] = { fg = p.violet },
        ["@namespace"] = { fg = p.teal, italic = true },
        ["@label"] = { link = "Label" },
        ["@exception"] = { link = "Exception" },

        ["@operator"] = { link = "Operator" },
        ["@punctuation.bracket"] = { fg = p.fg_alt },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Special" },
        ["@conceal"] = { link = "Conceal" },
        ["@strike"] = { strikethrough = true },
        ["@math"] = { link = "Special" },

        ["@tag"] = { link = "Tag" },
        ["@tag.builtin"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Attribute" },
        ["@tag.delimiter"] = { link = "Delimiter" },

        ["@comment"] = { link = "Comment" },
        ["@comment.documentation"] = { link = "Comment" },
        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "MoreMsg" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },

        ------------------------------------------------------------------
        -- Markup / text (markdown, rst, typst, help, ...)
        ------------------------------------------------------------------
        ["@markup.heading"] = { link = "Title" },
        ["@markup.heading.1"] = { link = "Title" },
        ["@markup.heading.2"] = { link = "Title" },
        ["@markup.heading.3"] = { link = "Title" },
        ["@markup.heading.4"] = { link = "Title" },
        ["@markup.heading.5"] = { link = "Title" },
        ["@markup.heading.6"] = { link = "Title" },
        ["@markup.strong"] = { bold = true },
        ["@markup.emphasis"] = { italic = true },
        ["@markup.italic"] = { italic = true },
        ["@markup.underline"] = { underline = true },
        ["@markup.strikethrough"] = { strikethrough = true },
        ["@markup.link"] = { link = "Link" },
        ["@markup.link.url"] = { fg = p.grey, underline = true },
        ["@markup.link.label"] = { fg = p.teal },
        ["@markup.list"] = { fg = p.teal },
        ["@markup.list.checked"] = { fg = p.green },
        ["@markup.list.unchecked"] = { fg = p.orange },
        ["@markup.note"] = { link = "SpecialComment" },
        ["@markup.quote"] = { fg = p.grey, italic = true },
        ["@markup.raw"] = { fg = p.green },
        ["@markup.raw.block"] = { fg = p.green },
        ["@markup.raw.delimiter"] = { fg = p.grey_dim },
        ["@markup.math"] = { fg = p.fg },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { fg = p.teal },

        ["@text"] = { link = "@none" },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.strong"] = { bold = true },
        ["@text.emphasis"] = { italic = true },
        ["@text.underline"] = { underline = true },
        ["@text.strike"] = { strikethrough = true },
        ["@text.math"] = { link = "Special" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { fg = p.green },
        ["@text.todo.unchecked"] = { fg = p.grey_dim },
        ["@text.uri"] = { link = "URL" },
        ["@todo"] = { link = "Todo" },

        ["@text.diff.add"] = { link = "@diff.plus" },
        ["@text.diff.delete"] = { link = "@diff.minus" },

        ["@diff.plus"] = { link = "DiffAdd" },
        ["@diff.minus"] = { link = "DiffDelete" },
        ["@diff.delta"] = { link = "DiffChange" },
    }
end

return M
